delete from "comercio-oltp".fornecedor;
;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(00 ,'editora lelivros');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(01 ,'editora mundo fantasia');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(02 ,'editora amazonia');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(03 ,'studios hb');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(04 ,'studios hollywood');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(05 ,'studios california');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(06 ,'em sports');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(07 ,'billzar games');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(08 ,'brazuca jogos');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(09 ,'jogar games');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(10 ,'motorola') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(11 ,'nokia') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(12 ,'samsung') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(13 ,'lg') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(14 ,'dreamc') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(15 ,'gforce') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(16 ,'apple') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(17 ,'sony') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(18 ,'wallita') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(19 ,'arno') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(20 ,'multilaser') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(21 ,'microsoft') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(22 ,'acer') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(23 ,'vision') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(24 ,'philips');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(25 ,'sandisk') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(26 ,'brastemp') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(27 ,'ganca') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(28 ,'britania') ;
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(29 ,'moveis varejão');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(30 ,'brasil madeiras');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(31 ,'linhas aéreas brazuca');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(32 ,'linhas brasil express');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(33 ,'linhas latinas de aviões');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(34 ,'linhas internacionais euro');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(35 ,'america lines express');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(36 ,'lenovo');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(37 ,'cce');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(38 ,'panasonic');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(39 ,'genius');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(40 ,'hp');
insert into "comercio-oltp".fornecedor( idfornecedor, nome)  OVERRIDING SYSTEM VALUE values(41 ,'brastemp');

