delete from "comercio-oltp".produto;

insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cavaleiro dos 7 reinos',30.00,15.00,1,1);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('jogos vorazes',45.00,22.00,1,1);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('revelados',48.00,24.00,1,1);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('a culpa é das estrelas',24.00,12.00,1,1);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('um caso perdido',56.00,20.00,1,1);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('windows 2016 visao geral',90.00,45.00,1,22);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('exchange 2014',130.00,90.00,1,22);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('c# pratico',60.00,45.00,1,22);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sql server 2016',30.00,15.00,1,22);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tsql tuning',90.00,75.00,1,22);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('advanced azure',70.00,55.00,1,22);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('as crônicas de andromeda',69.00,30.00,1,2);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cronicas antigas',189.00,60.00,1,2);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('o senhor do crime',199.00,120.00,1,3);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('barco de pedra',37.00,20.00,1,3);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('o patrão',78.00,50.00,2,4);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('a casa',299.00,140.00,2,5);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('a teoria',198.00,130.00,2,6);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('diário romântico',176.00,100.00,2,7);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('dinossauros',40.00,18.00,2,4);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('jackson',34.00,18.00,2,4);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('escolinha do juca',56.00,23.00,2,5);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('casoas antigos',37.00,20.00,2,7);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('o pequeno',43.00,23.00,2,7);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('poderoso chefe',98.00,46.00,2,5);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mentes criminosas',210.00,130.00,2,6);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('familia paratto',134.00,100.00,2,7);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('gladiadores',145.00,90.00,2,7);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('o super-herói',45.00,20.00,2,4);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('homem de aço',45.00,20.00,2,6);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('gravitacional',78.00,37.00,2,6);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('vingança',45.00,20.00,2,6);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('jogos maléficos',38.00,23.00,2,6);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('a vida secreta',37.00,21.00,2,7);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('o imortal',37.00,26.00,2,7);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cavaleiro das trevas',110.00,50.00,3,8);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cartoon movie',99.00,34.00,3,8);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cavaleiros de prata',145.00,89.00,3,8);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('wario',145.00,78.00,3,8);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('just dance',99.00,34.00,3,8);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('revivals',145.00,57.00,3,9);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('load runner',145.00,65.00,3,9);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('futebol 2018',145.00,67.00,3,10);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('soccer 2018',145.00,76.00,3,10);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('diabo',99.00,33.00,3,10);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('fantasy star',89.00,30.00,3,10);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('titans',98.00,50.00,3,9);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('raider',120.00,50.00,3,9);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('castelvania',120.00,53.00,3,10);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('south place',98.00,45.00,3,10);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('dragon blazer',90.00,40.00,3,9);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('thief',140.00,70.00,3,9);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('fabula',120.00,100.00,3,9);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('devilcry',120.00,65.00,3,9);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mafia',120.00,55.00,3,9);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('moto g6',860.00,620.00,4,11);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('moto g5',679.00,465.00,4,11);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('moto z play 2',1150.00,900.00,4,11);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('motorola tv',799.00,555.00,4,11);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('carregador turbo celular',99.00,55.00,4,11);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('nokia 549',450.00,300.00,4,12);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('nokia quarty',300.00,190.00,4,12);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('nokia asha 501',600.00,320.00,4,12);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('nokia asha 202',700.00,430.00,4,12);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('carregador universal nokia',100.00,60.00,4,12);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('samsung e1203',560.00,385.00,4,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('samsung xy 3',800.00,498.00,4,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('samsung xy 4',1200.00,965.00,4,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('samsung duos',1100.00,750.00,4,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('lg optimus',890.00,500.00,4,14);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('lg c397',500.00,360.00,4,14);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('dreamc vga',150.00,79.00,5,15);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('dreamc quarty',180.00,98.00,5,15);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('xtg e1',300.00,200.00,4,16);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('xtg sound',320.00,190.00,5,16);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('xtg rad d3',700.00,489.00,5,16);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('xtg rad d1',800.00,567.00,5,16);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('iphone 6',1900.00,1100.00,4,17);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('iphone 7',2500.00,1900.00,4,17);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('playstation 4',1980.00,990.00,3,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('playstation 3',980.00,590.00,3,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sony w100',980.00,530.00,4,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sony w200',1100.00,900.00,4,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sony w500',1200.00,780.00,4,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sony i7',2500.00,1300.00,5,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sony i5',1800.00,800.00,5,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('desktop i3',1800.00,986.00,5,23);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('desktop i5',2100.00,1020.00,5,23);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('desktop 17',2300.00,1800.00,5,23);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('ipod nano 16',300.00,110.00,5,17);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('ipod nano 32',450.00,320.00,5,17);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('ipad mini 16',1200.00,790.00,5,17);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('ipad 32',1900.00,1300.00,5,17);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('ipad 64',2500.00,1700.00,5,17);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('pendrive 32 multilaser',50.00,25.00,5,21);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('pendrive 16',30.00,10.00,5,25);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('pendrive 64',80.00,45.00,5,25);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('pendrive 64 ml',85.00,40.00,5,21);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('pendrive 256',240.00,190.00,5,25);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('pendrive 128 crossair',137.00,98.00,5,25);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('pendrive 128',146.00,100.00,5,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('hd 1t samsung',260.00,110.00,5,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('hd 2t samsung',550.00,200.00,5,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('hd 3t samsung',700.00,300.00,5,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('hd 1t',290.00,150.00,5,21);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('hd 2t',650.00,300.00,5,21);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('hd 3t',760.00,390.00,5,21);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('desktop p5 ml',1400.00,950.00,5,21);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('desktop a5 ml',1300.00,890.00,5,21);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('desktop p5 ph',1400.00,980.00,5,25);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('desktop a5 ph',1300.00,700.00,5,25);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('desktop a5 hp',1300.00,890.00,5,41);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('desktop p5 hp',1400.00,980.00,5,41);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('desktop a5 hp',1300.00,700.00,5,41);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook hp c-34',2300.00,1890.00,5,41);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook hp one',1870.00,1300.00,5,41);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook hp inove',3300.00,2700.00,5,41);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook sony jk',2800.00,1999.00,5,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook sony 3d',2500.00,2000.00,5,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook sony aws',2750.00,2400.00,5,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook msft hibr',4800.00,2999.00,5,22);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook msft touch',3500.00,2800.00,5,22);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook msft 17',3100.00,2700.00,5,22);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook acer 15',1500.00,800.00,5,23);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook acer 17',2100.00,1700.00,5,23);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook ln 15',1500.00,800.00,5,37);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('notebook ln 17',2100.00,1700.00,5,37);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tablet 7 lenovo',600.00,450.00,5,37);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tablet 10 lenovo',800.00,650.00,5,37);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mp4 32 gb sony',240.00,120.00,5,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('pc dual core',1350.00,890.00,5,25) ;
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('galaxy tab 10',2300.00,750.00,5,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('galaxy note',2900.00,1542.00,4,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('roteador wireless',90.00,38.00,5,21);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('roteador 18 portas',300.00,110.00,5,21);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('adaptador wireless',89.00,60.00,5,23);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('hub switch 6 portas',79.00,60.00,5,23);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('memoria ddr 3 4gb',80.00,45.00,5,24);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('memoria ddr 3 8gb',90.00,50.00,5,24);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('memoria ddr 3 16gb',140.00,75.00,5,24);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('memoria ddr 3 32gb',350.00,203.00,5,24);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('leitor de cartoes',34.00,10.00,5,24);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('leitor de cartoes multilaser',24.00,11.00,5,21);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cartao sd 32 gb sandisk',32.00,15.00,5,26);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cartao sd 64 gb samsung',78.00,55.00,5,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cartao sd 128 gb sandisk',156.00,99.00,5,26);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cartao sd 32 gb sandisk',32.00,15.00,5,26);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cartao sd 64 gb samsung',78.00,55.00,5,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cartao sd 128 gb sandisk',156.00,99.00,5,26) ;
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('placa de som',290.00,130.00,5,16);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('combo teclado e mouse',310.00,120.00,5,22);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('teclado wireless multilaser',120.00,90.00,5,21);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mouse optico',89.00,51.00,5,22);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('combo teclado e mouse',130.00,89.00,5,40);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('teclado wireless',89.00,70.00,5,40);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mouse optico',59.00,41.00,5,40);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mochila notebook 14 pol',89.00,61.00,5,40);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mochila notebook 15.6 pol',109.00,81.00,5,40);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mochila notebook 17 pol',139.00,91.00,5,40);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 42 sony',2000.00,1420.00,6,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 32 sony',1000.00,750.00,6,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 50 sony',3200.00,2465.00,6,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 60 sony',3900.00,3051.00,6,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 42 lg',2000.00,1620.00,6,14);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 32 lg',1100.00,850.00,6,14);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 50 lg',3100.00,2900.00,6,14);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 55 lg',3900.00,3050.00,6,14);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 42 samsung',2200.00,1354.00,6,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 32 samsung',1210.00,763.00,6,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 50 samsung',3300.00,2900.00,6,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 60 samsung',3800.00,3000.00,6,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv plasma philips 42',1200.00,980.00,6,25);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv led 42 cce',1600.00,800.00,6,38);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('home theater lg',230.00,100.00,6,14);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('home theater panasonic',245.00,150.00,6,39);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('smart tv philips 46',3199.00,2500.00,6,25);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('smart tv samsung 52',4300.00,3800.00,6,13);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('smart tv panasonic 46',3099.00,2500.00,6,39);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('smart tv panasonic 52',4200.00,3800.00,6,39);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('smart tv panasonic 32',1099.00,700.00,6,39);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('smart tv panasonic 42',2200.00,1800.00,6,39);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv 3d philips 42',3800.00,3201.00,6,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('tv 3d sony 42',3100.00,2684.00,6,18);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('lavadora lg 10l',2800.00,2186.00,7,14);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('geladeira brastemp',3000.00,2463.00,7,27);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('microondas brastemp',600.00,412.00,7,27);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('lavadora ganca 10l',5400.00,5020.00,7,28);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('chapa a gas ganca',1800.00,985.00,7,28);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('panificadora britania',250.00,130.00,7,29);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('grill geroge foreman',250.00,210.00,7,28);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mixer wallita',160.00,98.00,7,19);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mixer britania',90.00,68.00,7,29);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('liquidificador wallita',90.00,75.00,7,19);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('liquidificador arno',87.00,72.00,7,19);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('batedeira brastemp',120.00,95.00,7,27);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('juicer wallita',450.00,367.00,7,19);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('juicer arno',450.00,367.00,7,20);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('juicer cce',430.00,347.00,7,38);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('centrifuga arno',2800.00,2030.00,7,20);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('freezer 300l brastemp',1800.00,986.00,7,27);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('lava loucas brastemp',3500.00,2945.00,7,27);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('lava loucas cce',3600.00,2745.00,7,38);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mesa 4 lugares',1000.00,823.00,8,30);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cadeira de ferro',300.00,160.00,8,31);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mesa jantar 6 lugares',2500.00,1900.00,8,31);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('rack tv mogno',1500.00,1087.00,8,31);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('armario cozinha 6 portas',2500.00,2030.00,8,31);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('conjunto de sofa',3500.00,2954.00,8,31);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('mesa de centro',500.00,350.00,8,30);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cama solteiro',600.00,256.00,8,31);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('cama casal',1000.00,752.00,8,31);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sao paulo / recife',360.00,300.00,9,32);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sao paulo / goiania',400.00,360.00,9,32);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sao paulo / salvador',450.00,400.00,9,32);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sao paulo / rio de janeiro',230.00,180.00,9,33);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sao paulo / belo horizonte',250.00,200.00,9,33);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sao paulo / buenos aires',1090.00,1000.00,9,34);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sao paulo / lima',1900.00,1830.00,9,34);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sao paulo / miami',2300.00,2156.00,9,36);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sao paulo / madrid',2700.00,2350.00,9,35);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sao paulo / roma',2800.00,2400.00,9,35);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sao paulo / curitiba',300.00,260.00,9,33);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('sao paulo / londrina',310.00,280.00,9,33);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('rio de janeiro / campinas',250.00,210.00,9,34);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('rio de janeiro / lima',1900.00,1570.00,9,34);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('rio de janeiro / recife',560.00,500.00,9,34);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('rio de janeiro / curitiba',450.00,400.00,9,34);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('rio de janeiro / londrina',430.00,390.00,9,34);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('rio de janeiro / madrid',1800.00,1623.00,9,35);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('rio de janeiro / paris',2300.00,1980.00,9,35);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('rio de janeiro / miami',1900.00,1763.00,9,36);
insert into "comercio-oltp".produto( protudo, valor, custo_medio, id_categoria, id_fornecedor) values('rio de janeiro / new york',2600.00,2354.00,9,36);
;
